const CREATE_CHAT_MESSAGE = 'CREATE_CHAT_MESSAGE';
const CREATE_CHAT_MESSAGE_SUCCESS = 'CREATE_CHAT_MESSAGE_SUCCESS';
const CREATE_CHAT_MESSAGE_FAILURE = 'CREATE_CHAT_MESSAGE_FAILURE';

module.exports = {
    CREATE_CHAT_MESSAGE,
    CREATE_CHAT_MESSAGE_SUCCESS,
    CREATE_CHAT_MESSAGE_FAILURE
};
