const USER_CONNECTED = 'USER_CONNECTED';
const USER_DISCONNECTED = 'USER_DISCONNECTED';
const CREATE_CHAT_MESSAGE = 'CREATE_CHAT_MESSAGE';
const CREATE_CHAT_MESSAGE_SUCCESS = 'CREATE_CHAT_MESSAGE_SUCCESS';
const CREATE_CHAT_MESSAGE_FAILURE = 'CREATE_CHAT_MESSAGE_FAILURE';

module.exports = {
    USER_CONNECTED,
    USER_DISCONNECTED,
    CREATE_CHAT_MESSAGE,
    CREATE_CHAT_MESSAGE_SUCCESS,
    CREATE_CHAT_MESSAGE_FAILURE
};
